---
username: your twitter id here
password: your twitter password here
title: a title
subtitle: some witty subtitle
template: index.tt
output: index.html
# number of tweets to display (defaults to 20)
tweets: 
# I use this to trigger the addition of Google Analytics code
# Obviously it's optional
analytics_id: 
