---
title: a title
subtitle: some witty subtitle
template: index.tt
output: index.html
# number of tweets to display (defaults to 20)
tweets: 
# I use this to trigger the addition of Google Analytics code
# Obviously it's optional
analytics_id: 
# You get these from Twitter when you register your new
# app at http://twitter.com/apps/new`
consumer_key: 
consumer_secret:
